### ISSUE TITLE
Unable to change appearance settings

### ISSUE THREAD

**Issue by petersadik** [Dinir/mini-padder#20]
Thank you for making this, it looks super clean. I may just be dumb, but hope you can help me out.

So I am trying to change the fade settings to fade faster. On the minipadder website, the fade settings update correctly, but when I paste the link (https://minipadder.link/) into OBS as a browser source, it keeps the default fade settings.

I tried right clicking the source then going to 'Interact' but all it shows is a window with the controller overlay. I can't seem to change any settings in the interact window.

I could try giving more details if that doesn't make sense. Thanks!

**Comment by Dinir** [comment]
Hello, thanks for finding and trying Mini Padder.

The settings are saved per-browser, so you want to make initial set up after loading it into OBS. If the interact window is only showing the controller overlay (do you mean the actual animated part?), I guess the browser source should be larger to show the control panel.

Try changing the size from the source's properties window to 1048x600, then see if you can see the control panel and make changes there in the window. You can then crop the controller overlay part using other methods like Transform menu.

**Comment by petersadik** [comment]
Ah, okay the editting menu is showing up now. I just set the source size to 1048x600 like you said. Thank you!
