### ISSUE TITLE
OBS/Chrome behavior's differ

### ISSUE THREAD

**Issue by borlonty** [Dinir/mini-padder#21]
**Describe the bug**
Not sure if this is a bug or a setting I'm not using. When I upload the browser capture to OBS, it does not register the left or right dpad as being pressed. when I use the up dpad it registers as the home button (PS button) and when I push up, it registers as the touchpad. However, when I have it open on chrome, it registers all buttons.

**Expected behavior**
I expected it to register on OBS the same as the Chrome page.

**Browser** 
OBS 29.0.2
Chrome: Version 113.0.5672.63 (Official Build) (64-bit)

**Troubleshooting**
I tried restarting both the webpage as well as deleting/readding the OBS link.

**Screenshots**
![image](https://user-images.githubusercontent.com/132786458/236646480-e03891ba-ec84-4736-ab1f-ba013de5fbc5.png)
![image](https://user-images.githubusercontent.com/132786458/236646499-e7290b9c-0390-4192-b3a8-ad2d80e842a2.png)

**Comment by Dinir** [comment]
If the exact same gamepad is producing different results in OBS and Chrome, it would be helpful to know what your gamepad and how the button assignment for the gamepad Mini Padder produces is on both places.

I can't provide a reasonably fast help in regard to this, but for now please try assigning buttons manually and see if it makes the buttons on the gamepad all working properly.
