### ISSUE TITLE
Nintendo Switch Pro Controller not detecting sticks or D-pad

### ISSUE THREAD

**Issue by JapanYoshi** [Dinir/mini-padder#24]
**Describe the bug**
When using the tool on the Nintendo Switch Pro Controller, the face buttons, - and + buttons, stick press buttons, and shoulder buttons are correctly detected. However, Home and Screenshot are incorrectly detected as D-pad up and down. The D-pad and both sticks are not detected at all.

I tried to use the key mapping wizard, but when I pressed the A button, it aborted.

**Expected behavior**
The tool should be compatible with the Pro Controller; after all, there's a preset for it in the stetings.

**Browser** 
Firefox 125.0.2 for Windows 10

**To Reproduce**
1. Connect a Switch Pro Controller, or a controller that simulates one like 8BitDo Ultimate or 8BitDo Lite in S mode
2. Press the D-pad or move the joysticks.

**Screenshots**

- - -

**Comment by Dinir** [comment]
Have you tried pressing other buttons when trying the key mapping?
Nintendo gamepad scheme has A and B in the opposite position of XBox
gamepads.

**Comment by JapanYoshi** [comment]
I don’t think you understand the issue.

**Comment by Dinir** [comment]
Ok, thanks for the clarification.
